; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "BDSAX - Banco de Dados Sistema Acadêmico eXpresso para IEs"
#define MyAppVersion "1.1"
#define MyAppPublisher "Silas Silva"
#define MyAppURL "http://silao.com.br:8080/apex"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DE71A8A8-422C-4CC9-8840-64ACB36F3A4E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
LicenseFile=C:\sax\install\script\lic.txt
InfoBeforeFile=C:\sax\install\script\antes.txt
InfoAfterFile=C:\sax\install\script\depois.txt
OutputBaseFilename=bdsetup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Files]
Source: "C:\sax\install\script\antes.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\sax\install\script\depois.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\sax\install\script\dminstall.sql"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\sax\install\script\install.sql"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\sax\install\script\lic.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\sax\install\script\popula_MUNIs_censo.sql"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\sax\install\script\popula_paises_censo.sql"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\sax\install\script\POPULA_REFERENCIAS.SQL"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\sax\install\script\popula_ufs_censo.sql"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\sax\install\script\tablespaces.sql"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\sax\install\script\userrole.sql"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\sax\install\script\VW_ALUNO.SQL"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\sax\install\script\VW_CURSO_ALUNO.SQL"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\sax\install\script\VW_DOCENTE.SQL"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\sax\install\script\install_release1_0.sql"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\sax\install\script\bdinstall.bat"; DestDir: "{app}"; Flags: ignoreversion

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Run]
Filename: "{app}\bdinstall.bat"; WorkingDir:"{app}"; StatusMsg:"Instalando Software SAX para IEs"; Parameters: "sys/Kr4!th0s"

[Icons]
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"

