REM "-- -------------------------------------------------------------------- --"
REM " SCRIPT PARA CRIAÇÃO DA TABELA DE ENDEREÇOS COM BASE NO WEBSERVICE VIACEP "
REM " SAX - RELEASE 1.0                                                        "
REM " AUTOR: SILAS SILVA 09/05/2017                                            "
REM "-- -------------------------------------------------------------------- --"
prompt Executando install_release1_0...
column arquivo new_val arquivo
select 'C:\SAX\INSTALL\LOG\install_release1_0_' || to_char(sysdate, 'yyyymmddhh24mi') || '.log' arquivo from dual;
spool &arquivo;

Alter Session Set nls_language='BRAZILIAN PORTUGUESE';
Alter Session Set NLS_TERRITORY = 'BRAZIL';
Alter Session Set NLS_NUMERIC_CHARACTERS=',.';
Alter Session Set NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

DROP TABLE TBL_ENDERECO CASCADE CONSTRAINTS;
DROP SEQUENCE SQ_ENDERECO;

DELETE FROM TBL_REFERENCIA
 WHERE REFE_ST_TIPO = 'TIPO_ENDERECO';
 
INSERT INTO TBL_REFERENCIA(REFE_IN_ID, REFE_ST_TIPO , REFE_IN_CODIGO , REFE_ST_DESCRICAO, user_st_atualiza, user_dt_atualiza)
VALUES (SQ_REFERENCIA.NEXTVAL , 'TIPO_ENDERECO' , 1, 'Instituição', 'ADMIN', SYSDATE);

INSERT INTO TBL_REFERENCIA(REFE_IN_ID, REFE_ST_TIPO , REFE_IN_CODIGO , REFE_ST_DESCRICAO, user_st_atualiza, user_dt_atualiza)
VALUES (SQ_REFERENCIA.NEXTVAL , 'TIPO_ENDERECO' , 2, 'Docente', 'ADMIN', SYSDATE);

INSERT INTO TBL_REFERENCIA(REFE_IN_ID, REFE_ST_TIPO , REFE_IN_CODIGO , REFE_ST_DESCRICAO, user_st_atualiza, user_dt_atualiza)
VALUES (SQ_REFERENCIA.NEXTVAL , 'TIPO_ENDERECO' , 3, 'Aluno', 'ADMIN', SYSDATE);

CREATE TABLE TBL_ENDERECO (ENDR_IN_ID INTEGER NOT NULL,
                           ENDR_IN_CEP NUMBER(8) NOT NULL,
						   ENDR_IN_TIPO_REFERENCIA INTEGER,
						   ENDR_IN_REFERENCIA INTEGER,
						   ENDR_ST_LOGRADOURO VARCHAR2(255) NOT NULL,
						   ENDR_IN_NUMERO NUMBER NULL,
						   ENDR_ST_COMPLEMENTO VARCHAR2(255) NULL,					   ENDR_ST_BAIRRO VARCHAR2(255) NULL,
						   MUNI_IN_CODIGO_CENSO NUMBER NOT NULL,
						   ENDR_ST_UF   CHAR(2) NOT NULL,
						   USER_ST_ATUALIZA VARCHAR2(30) NOT NULL,
						   USER_DT_ATUALIZA DATE NOT NULL)
/

create SEQUENCE SQ_ENDERECO START WITH 1 INCREMENT BY 1 NOCACHE ORDER;
  
ALTER TABLE TBL_ENDERECO
  ADD CONSTRAINT PK_ENDR PRIMARY KEY (ENDR_IN_ID) 
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
/

ALTER TABLE TBL_ENDERECO
  ADD CONSTRAINT UK_ENDR_TIPO_REFERENCIA UNIQUE (ENDR_IN_TIPO_REFERENCIA, ENDR_IN_REFERENCIA) 
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
/


ALTER TABLE TBL_ENDERECO
  ADD CONSTRAINT FK_ENDR_MUNICIPIO FOREIGN KEY (MUNI_IN_CODIGO_CENSO) REFERENCES TBL_MUNICIPIO
/

COMMENT ON TABLE TBL_ENDERECO                     IS 'Tabela de Endereços';
COMMENT ON COLUMN TBL_ENDERECO.ENDR_IN_ID         IS 'Identificador Único do Endereço';
COMMENT ON COLUMN TBL_ENDERECO.ENDR_IN_CEP        IS 'CEP do Endereço BASEADO no webservice dos correios (viacep)';
COMMENT ON COLUMN TBL_ENDERECO.ENDR_ST_LOGRADOURO IS 'LOGRADOURO BASEADO no webservice dos correios (viacep)';
COMMENT ON COLUMN TBL_ENDERECO.ENDR_ST_COMPLEMENTO IS 'COMPLEMENTO DO LOGRADOURO BASEADO no webservice dos correios (viacep)';
COMMENT ON COLUMN TBL_ENDERECO.ENDR_IN_NUMERO     IS 'NUMERO DO LOGRADOURO.';
COMMENT ON COLUMN TBL_ENDERECO.ENDR_ST_BAIRRO     IS 'NOME DO BAIRRO DO LOGRADOURO.';
COMMENT ON COLUMN TBL_ENDERECO.MUNI_IN_CODIGO_CENSO IS 'CÓDIGO IBGE DO MUNICIPIO NO CENSO DO ENSINO SUPERIOR.';
COMMENT ON COLUMN TBL_ENDERECO.USER_ST_ATUALIZA   IS 'USUÁRIO QUE ATUALIZOU O REGISTRO.';
COMMENT ON COLUMN TBL_ENDERECO.USER_DT_ATUALIZA   IS 'DATA EM QUE O REGISTRO FOI ATUALIZADO.';
COMMENT ON COLUMN TBL_ENDERECO.ENDR_IN_TIPO_REFERENCIA   IS 'ID DO TIPO DE REFERENCIA 1 - INSTITUICAO 2 - DOCENTE 3 -ALUNO';
COMMENT ON COLUMN TBL_ENDERECO.ENDR_IN_REFERENCIA   IS 'ID Da REFERENCIA ID DA INSTITUICAO OU DO DOCENTE OU DO ALUNO';


CREATE OR REPLACE TRIGGER TRG_BIU_ENDERECO BEFORE
  INSERT or UPDATE ON TBL_ENDERECO FOR EACH ROW
BEGIN 
  IF :NEW.ENDR_IN_ID IS NULL THEN
    SELECT SQ_ENDERECO.NEXTVAL INTO :NEW.ENDR_IN_ID FROM DUAL;
  END IF;
  PC_ATUALIZA_USUARIO(:NEW.USER_ST_ATUALIZA,:NEW.USER_DT_ATUALIZA);
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
          WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20001,'ERRO NA EXECUÇÃO DA TRIGGER VALORES => '||:NEW.ENDR_IN_TIPO_REFERENCIA||','||:NEW.ENDR_IN_REFERENCIA||','||:NEW.ENDR_IN_ID||',"'||:NEW.USER_ST_ATUALIZA||'"  ');
END;
/
show errors;

-- Features 7 e 8 - Alterar o Prazo Mínimo de Integralização de Carga Horária para semestres.
-- Transferir o Prazo Mínimo de Integralização e Máximo da tabela de curso_turno para a tabela de currículo.

alter table tbl_curso_turno
 drop column IN_PRAZO_MINIMO_INTEGRA; 

alter table tbl_curso_turno
 drop column IN_PRAZO_MAXIMO_INTEGRA; 

alter table tbl_curriculo
  add CURR_IN_PRAZO_MIN_INTEGRA NUMBER;
  
alter table tbl_curriculo
  add CURR_IN_PRAZO_MAX_INTEGRA NUMBER;
 
-- Prazo Máximo de Integralização: Caso o prazo máximo não for informado assume como padrão PRAZO MÁXIMO = PRAZO_MINIMO + (1/2) * PRAZO_MINIMO 
CREATE OR REPLACE TRIGGER TRG_BIU_CURRICULO BEFORE
  INSERT or UPDATE ON TBL_CURRICULO FOR EACH ROW
BEGIN 
  PC_ATUALIZA_USUARIO(:NEW.USER_ST_ATUALIZA,:NEW.USER_DT_ATUALIZA);
  -- Feature 8 - Prazo Máximo de Integralização.
  IF :NEW.CURR_IN_PRAZO_MAX_INTEGRA IS NULL AND :NEW.CURR_IN_PRAZO_MIN_INTEGRA IS NOT NULL THEN
	:NEW.CURR_IN_PRAZO_MAX_INTEGRA := (:NEW.CURR_IN_PRAZO_MIN_INTEGRA + ROUND(:NEW.CURR_IN_PRAZO_MIN_INTEGRA/2));
  END IF;
END;
/  
  
-- Feature x
alter table tbl_aluno add ALU_BL_FOTO VARCHAR2(255);
alter table tbl_aluno add ALU_ST_FOTO_FILENAME VARCHAR2(255);

alter table tbl_docente add DOCE_BL_FOTO VARCHAR2(255);
alter table tbl_docente add DOCE_ST_FOTO_FILENAME VARCHAR2(255);

alter table tbl_aluno add ALU_ST_FOTO_MIMETYPE VARCHAR2(255);
alter table tbl_aluno add ALU_DT_FOTO_ULTIMAATLZ DATE;

alter table tbl_docente add DOCE_ST_FOTO_MIMETYPE VARCHAR2(255);
alter table tbl_docente add DOCE_DT_FOTO_ULTIMAATLZ DATE;
 
-- Procedure para Excluir FOTO do Aluno / Professor.
create or replace procedure PC_EXCLUIR_FOTO(PI_ST_TABELA VARCHAR2, PI_ST_COLUNA_BLOB VARCHAR2, PI_ST_COLUNA_ID VARCHAR2, PI_IN_ID INTEGER)  is
	begin
		execute immediate 'UPDATE '||PI_ST_TABELA||' SET '||PI_ST_COLUNA_BLOB||' = EMPTY_BLOB() WHERE '||PI_ST_COLUNA_ID||' = '||PI_IN_ID;
	end;
	
-- Feature 10
-- Adicionar campos duração de aulas e quantidade de aulas no semestre.
alter table tbl_disciplina
  add disc_nu_duracao_aula number;

alter table tbl_disciplina
  add disc_nu_qtde_aula_semestre integer;
  
-- Feature 11
-- Adicionar campo Tipo de Disciplina no cadastro de formulas.
alter table tbl_formula_media
  add fmed_in_tipo_disciplina integer;

  alter table TBL_REFERENCIA
  add refe_st_descricao_correspond VARCHAR2(255);
  
INSERT INTO TBL_REFERENCIA
   (REFE_IN_ID, REFE_ST_TIPO, REFE_IN_CODIGO, REFE_ST_DESCRICAO, REFE_ST_DESCRICAO_CORRESPOND, USER_ST_ATUALIZA, USER_DT_ATUALIZA)
VALUES  
   (SQ_REFERENCIA.NEXTVAL, 'FUNCAO_FORMULA_MEDIA', 1, '(FX) FC_HORAS_TOTAIS', 'FC_HORAS_TOTAIS(:w_curr_in_id,:w_disc_in_id)', USER, SYSDATE);

INSERT INTO TBL_REFERENCIA
   (REFE_IN_ID, REFE_ST_TIPO, REFE_IN_CODIGO, REFE_ST_DESCRICAO, REFE_ST_DESCRICAO_CORRESPOND, USER_ST_ATUALIZA, USER_DT_ATUALIZA)
VALUES  
   (SQ_REFERENCIA.NEXTVAL, 'FUNCAO_FORMULA_MEDIA', 2, '(FX) FC_HORAS_SEMESTRE', 'FC_HORAS_SEMESTRE(:w_curr_in_id,:w_disc_in_id,:w_in_periodo)', USER, SYSDATE);

commit;

ALTER TABLE TBL_FORMULA_MEDIA MODIFY FMED_IN_MODALIDADE NULL;

CREATE OR REPLACE FUNCTION FC_HORAS_SEMESTRE(PI_ACUR_IN_ID INTEGER, 
                                             PI_CURR_IN_ID INTEGER, 
											 PI_DISC_IN_ID INTEGER, 
											 PI_IN_PERIODO INTEGER DEFAULT NULL, 
											 PI_ACHIS_NU_CHTEORICA_CUMPRIDA NUMBER, 
											 PI_ACHIS_NU_CHPRATICA_CUMPRIDA NUMBER, 
											 PI_ACHIS_IN_SITUACAO INTEGER) RETURN NUMBER IS
  CURSOR C_TOTAL_HORAS IS
     select D.DIS_IN_TIPO
      from TBL_DISCIPLINA D
     WHERE D.DISC_IN_ID = PI_DISC_IN_ID;
  W_TOTAL_HORAS_SEM TBL_ALUNO_CURSO_HISTORICO.ACHIS_NU_CHTEORICA_CUMPRIDA%TYPE;
  W_DIS_IN_TIPO TBL_DISCIPLINA.DIS_IN_TIPO%TYPE;
BEGIN
  IF PI_ACHIS_IN_SITUACAO IN (3,5) THEN /*APROVADO OU DISPENSADO ACUMULA HORAS */
     IF W_DIS_IN_TIPO = 3 THEN /*3=PRATICA;4=TEORICO-PRATICA*/
       	W_TOTAL_HORAS_SEM := PI_ACHIS_NU_CHPRATICA_CUMPRIDA;
	 ELSE
       	W_TOTAL_HORAS_SEM := PI_ACHIS_NU_CHTEORICA_CUMPRIDA;
	 END IF;
  END IF;
  RETURN W_TOTAL_HORAS_SEM;
END;
/
SHOW ERRORS;

CREATE OR REPLACE FUNCTION FC_HORAS_TOTAIS(PI_CURR_IN_ID INTEGER, PI_DISC_IN_ID INTEGER) RETURN NUMBER IS
  W_TOTAL_HORAS TBL_ALUNO_CURSO_HISTORICO.ACHIS_NU_CHTEORICA_CUMPRIDA%TYPE:=0;
  CURSOR C_HORAS_TOTAIS IS
  SELECT CASE D.DIS_IN_TIPO
         WHEN 3 THEN G.GRD_IN_CARGA_HRPRATICA
		 ELSE G.GRD_IN_CARGA_HORARIA
		 END CARGA_HORARIA
    FROM TBL_GRADE G, TBL_DISCIPLINA D
   WHERE D.DISC_IN_ID = G.DISC_IN_ID
     AND G.CURR_IN_ID = PI_CURR_IN_ID
     AND G.DISC_IN_ID = PI_DISC_IN_ID;
BEGIN
  OPEN C_HORAS_TOTAIS;
  FETCH C_HORAS_TOTAIS INTO W_TOTAL_HORAS;
  CLOSE C_HORAS_TOTAIS;
  RETURN W_TOTAL_HORAS;
END;
/
SHOW ERRORS;

INSERT INTO TBL_REFERENCIA(REFE_IN_ID, REFE_ST_TIPO , REFE_IN_CODIGO , REFE_ST_DESCRICAO, user_st_atualiza, user_dt_atualiza)
VALUES (SQ_REFERENCIA.NEXTVAL , 'SITUACAO_ALUNO' , 7, 'Falecido', 'ADMIN', SYSDATE);

INSERT INTO TBL_REFERENCIA(REFE_IN_ID, REFE_ST_TIPO , REFE_IN_CODIGO , REFE_ST_DESCRICAO, user_st_atualiza, user_dt_atualiza)
VALUES (SQ_REFERENCIA.NEXTVAL , 'GRAU_CURSO' , 1, 'Graduação', 'ADMIN', SYSDATE);

INSERT INTO TBL_REFERENCIA(REFE_IN_ID, REFE_ST_TIPO , REFE_IN_CODIGO , REFE_ST_DESCRICAO, user_st_atualiza, user_dt_atualiza)
VALUES (SQ_REFERENCIA.NEXTVAL , 'GRAU_CURSO' , 2, 'Pós-Graduação (Latu Sensu)', 'ADMIN', SYSDATE);

INSERT INTO TBL_REFERENCIA(REFE_IN_ID, REFE_ST_TIPO , REFE_IN_CODIGO , REFE_ST_DESCRICAO, user_st_atualiza, user_dt_atualiza)
VALUES (SQ_REFERENCIA.NEXTVAL , 'GRAU_CURSO' , 3, 'Pós-Graduação (Strictu Sensu)', 'ADMIN', SYSDATE);

INSERT INTO TBL_REFERENCIA(REFE_IN_ID, REFE_ST_TIPO , REFE_IN_CODIGO , REFE_ST_DESCRICAO, user_st_atualiza, user_dt_atualiza)
VALUES (SQ_REFERENCIA.NEXTVAL , 'GRAU_CURSO' , 4, 'Extensão', 'ADMIN', SYSDATE);


alter table tbl_curso add cur_in_grau integer;

update tbl_curso set cur_in_grau = 1;

alter table tbl_curso modify cur_in_grau default 1 not null;

create table TBL_PROCESSO_SELETIVO (PSEL_IN_ID INTEGER NOT NULL,
                                    ACUR_IN_ID INTEGER NOT NULL,
                                    PSEL_IN_TIPO INTEGER NOT NULL,
									PSEL_DT_DATA_AVAL DATE NOT NULL,
									PSEL_IN_CLASSIFICACAO INTEGER NULL,
									PSEL_NU_NOTA_REDACAO  NUMBER NULL,
									PSEL_ST_LOCAL VARCHAR2(255),
									PSEL_IN_UF INTEGER,
									PSEL_IN_MUNICIPIO INTEGER,
									USER_ST_ATUALIZA  VARCHAR2(30) NOT NULL,
									USER_DT_ATUALIZA  DATE NOT NULL)
 /

create SEQUENCE SQ_PROCESSO_SELETIVO START WITH 1 INCREMENT BY 1 NOCACHE ORDER;

ALTER TABLE TBL_PROCESSO_SELETIVO
  ADD CONSTRAINT PK_PSEL PRIMARY KEY (PSEL_IN_ID) 
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
/

ALTER TABLE TBL_PROCESSO_SELETIVO
  ADD CONSTRAINT FK_PSEL_ACUR FOREIGN KEY (ACUR_IN_ID) REFERENCES TBL_ALUNO_CURSO
/

COMMENT ON TABLE TBL_PROCESSO_SELETIVO                        IS 'Processo Seletivo do Aluno no Curso';
COMMENT ON COLUMN TBL_PROCESSO_SELETIVO.PSEL_IN_ID            IS 'Id Interno do Processo Seletivo';
COMMENT ON COLUMN TBL_PROCESSO_SELETIVO.ACUR_IN_ID            IS 'Id Interno do Aluno no Curso';
COMMENT ON COLUMN TBL_PROCESSO_SELETIVO.PSEL_IN_TIPO          IS 'Id Interno do Tipo de Processo Seletivo (Tipo de Ingresso)';
COMMENT ON COLUMN TBL_PROCESSO_SELETIVO.PSEL_DT_DATA_AVAL     IS 'Data da Avaliação';
COMMENT ON COLUMN TBL_PROCESSO_SELETIVO.PSEL_IN_CLASSIFICACAO IS 'Classificação no Processo Seletivo';
COMMENT ON COLUMN TBL_PROCESSO_SELETIVO.PSEL_NU_NOTA_REDACAO  IS 'Nota da Redação';
COMMENT ON COLUMN TBL_PROCESSO_SELETIVO.PSEL_ST_LOCAL         IS 'Local da Aplicação do Processo Seletivo';
COMMENT ON COLUMN TBL_PROCESSO_SELETIVO.PSEL_IN_UF            IS 'UF do Local da Aplicação do Processo Seletivo';
COMMENT ON COLUMN TBL_PROCESSO_SELETIVO.PSEL_IN_MUNICIPIO     IS 'MUNICÍPIO do Local da Aplicação do Processo Seletivo';
COMMENT ON COLUMN TBL_PROCESSO_SELETIVO.USER_ST_ATUALIZA      IS 'Usuário que fez a atualização';
COMMENT ON COLUMN TBL_PROCESSO_SELETIVO.USER_DT_ATUALIZA      IS 'Data em que fez a atualização';

CREATE OR REPLACE TRIGGER TRG_BIU_PROCESSO_SELETIVO BEFORE
  INSERT or UPDATE ON TBL_PROCESSO_SELETIVO FOR EACH ROW
BEGIN 
  PC_ATUALIZA_USUARIO(:NEW.USER_ST_ATUALIZA,:NEW.USER_DT_ATUALIZA);
END;
/  

ALTER TABLE TBL_INSTITUICAO
  ADD INST_ST_ATONORMATIVO VARCHAR2(255);

ALTER TABLE TBL_INSTITUICAO
  ADD INST_DT_EXPED_ATONORMATIVO DATE;

ALTER TABLE TBL_INSTITUICAO
  ADD INST_DT_PUBLI_ATONORMATIVO DATE;

 
COMMENT ON COLUMN TBL_INSTITUICAO.INST_ST_ATONORMATIVO IS 'Descrição do Ato Normativo da Instituição de Ensino';  
COMMENT ON COLUMN TBL_INSTITUICAO.INST_DT_EXPED_ATONORMATIVO IS 'Data da Expedição do Ato Normativo';  
COMMENT ON COLUMN TBL_INSTITUICAO.INST_DT_PUBLI_ATONORMATIVO IS 'Data da Publicação em Diário Oficial do Ato Normativo';  

ALTER TABLE TBL_INSTITUICAO
  ADD INST_ST_NOME_DIRET VARCHAR2(255);
  
ALTER TABLE TBL_INSTITUICAO
  ADD INST_ST_NOME_SECRET VARCHAR2(255);

COMMENT ON COLUMN TBL_INSTITUICAO.INST_ST_NOME_SECRET IS 'Nome Secretária ou Secretário Acadêmico';  
COMMENT ON COLUMN TBL_INSTITUICAO.INST_ST_NOME_DIRET IS 'Nome Diretora/Reitora ou Diretor/Reitor Acadêmico';  

ALTER TABLE TBL_GRADE add CONSTRAINT UK_GRADE_DISCIPLINA UNIQUE(CURR_IN_ID,DISC_IN_ID);

ALTER TABLE TBL_ALUNO_CURSO_HISTORICO
  ADD ACHIS_IN_SITUACAO_PRATICA INTEGER;

INSERT INTO TBL_REFERENCIA(REFE_IN_ID, REFE_ST_TIPO , REFE_IN_CODIGO , REFE_ST_DESCRICAO, user_st_atualiza, user_dt_atualiza)
VALUES (SQ_REFERENCIA.NEXTVAL , 'SITUACAO_PRATICA' , 0, 'Não Cumpriu', 'ADMIN', SYSDATE);

INSERT INTO TBL_REFERENCIA(REFE_IN_ID, REFE_ST_TIPO , REFE_IN_CODIGO , REFE_ST_DESCRICAO, user_st_atualiza, user_dt_atualiza)
VALUES (SQ_REFERENCIA.NEXTVAL , 'SITUACAO_PRATICA' , 1, 'Cumpriu', 'ADMIN', SYSDATE);

UPDATE TBL_REFERENCIA
   SET REFE_ST_DESCRICAO_CORRESPOND = 'FC_HORAS_TOTAIS(:p_curriculo,:p_disciplina)'
 WHERE REFE_ST_TIPO = 'FUNCAO_FORMULA_MEDIA'
   AND REFE_IN_CODIGO = 1;

UPDATE TBL_REFERENCIA
   SET REFE_ST_DESCRICAO_CORRESPOND = 'FC_HORAS_SEMESTRE(:p_alunocurso,:p_curriculo,:p_disciplilna,:p_periodo,:p_ch_teorica_cumprida,:p_ch_pratica_cumprida,:p_situacao)'
 WHERE REFE_ST_TIPO = 'FUNCAO_FORMULA_MEDIA'
   AND REFE_IN_CODIGO = 2;

/*
@C:\sax\install\scripts\TRG_BIU_ALUNO_HISTORICO.SQL;
@C:\sax\install\scripts\TABLES_CENSO.SQL;
@C:\sax\install\scripts\PKG_CENSO.SQL;
*/  
SPOOL OFF;
