CREATE OR REPLACE PROCEDURE PC_POPULA_FERIADO_CALENDARIO(P_ANO INTEGER, P_INST_IN_ID INTEGER) IS
  CURSOR C_FERI IS SELECT * FROM TBL_FERIADO;
  W_CALE_IN_ID TBL_CALENDARIO.CALE_IN_ID%TYPE;
BEGIN
  FOR CL IN C_FERI LOOP
    BEGIN
	  SELECT SQ_CALENDARIO.NEXTVAL INTO W_CALE_IN_ID FROM DUAL;
	  INSERT INTO TBL_CALENDARIO(
		CALE_IN_ID, 
		CALE_IN_ANO, 
		INST_IN_ID, 
		CALE_ST_DESCRICAO, 
		CALE_DT_INICIO, 
		CALE_DT_FIM, 
		CALE_IN_TIPO_DATA, 
		USER_ST_ATUALIZA, 
		USER_DT_ATUALIZA)
	  VALUES (
		W_CALE_IN_ID, 
		P_ANO, 
		P_INST_IN_ID, 
		CL.FER_ST_NOME, 
		TO_DATE(P_ANO||LPAD(TO_CHAR(CL.FER_IN_MES),2,'0')||LPAD(TO_CHAR(CL.FER_IN_DIA),2,'0'),'YYYYMMDD'),
		TO_DATE(P_ANO||LPAD(TO_CHAR(CL.FER_IN_MES),2,'0')||LPAD(TO_CHAR(CL.FER_IN_DIA),2,'0'),'YYYYMMDD'),
		2,
		'ADMIN',
		SYSDATE);
	END;
  END LOOP;
END;