INSERT INTO TBL_FERIADO (FER_IN_ID, FER_ST_NOME, FER_IN_MES, FER_IN_DIA, USER_ST_ATUALIZA, USER_DT_ATUALIZA)
VALUES (SQ_FERIADO.NEXTVAL, 'Confraternização Universal - Ano Novo', 1, 1, 'ADMIN', SYSDATE);

INSERT INTO TBL_FERIADO (FER_IN_ID, FER_ST_NOME, FER_IN_MES, FER_IN_DIA, USER_ST_ATUALIZA, USER_DT_ATUALIZA)
VALUES (SQ_FERIADO.NEXTVAL, 'Tiradentes', 4, 21, 'ADMIN', SYSDATE);

INSERT INTO TBL_FERIADO (FER_IN_ID, FER_ST_NOME, FER_IN_MES, FER_IN_DIA, USER_ST_ATUALIZA, USER_DT_ATUALIZA)
VALUES (SQ_FERIADO.NEXTVAL, 'Dia do Trabalho', 5, 1, 'ADMIN', SYSDATE);

INSERT INTO TBL_FERIADO (FER_IN_ID, FER_ST_NOME, FER_IN_MES, FER_IN_DIA, USER_ST_ATUALIZA, USER_DT_ATUALIZA)
VALUES (SQ_FERIADO.NEXTVAL, 'Independência do Brasil', 9, 7, 'ADMIN', SYSDATE);

INSERT INTO TBL_FERIADO (FER_IN_ID, FER_ST_NOME, FER_IN_MES, FER_IN_DIA, USER_ST_ATUALIZA, USER_DT_ATUALIZA)
VALUES (SQ_FERIADO.NEXTVAL, 'Nossa Senhora Aparecida', 10, 12, 'ADMIN', SYSDATE);


INSERT INTO TBL_FERIADO (FER_IN_ID, FER_ST_NOME, FER_IN_MES, FER_IN_DIA, USER_ST_ATUALIZA, USER_DT_ATUALIZA)
VALUES (SQ_FERIADO.NEXTVAL, 'Proclamação da República', 11, 15, 'ADMIN', SYSDATE);

INSERT INTO TBL_FERIADO (FER_IN_ID, FER_ST_NOME, FER_IN_MES, FER_IN_DIA, USER_ST_ATUALIZA, USER_DT_ATUALIZA)
VALUES (SQ_FERIADO.NEXTVAL, 'Natal', 12, 25, 'ADMIN', SYSDATE);

