SELECT ALUX.ALU_ST_NOME ALU_ST_NOME	 
     , ALUX.ALU_ST_RG ALU_ST_RG
     , ALUX.ALU_IN_RGM ALU_IN_RGM
     , FC_REFERENCIA_DESCRICAO('NACIONALIDADE',ALUX.ALU_IN_NACIONALIDADE) ALU_NACIONALIDADE 
     , TO_CHAR(ALUX.ALU_DT_NASCIMENTO,'DD/MM/YYYY') ALU_DT_NASCIMENTO
     , UFX.UF_ST_NOME         UF_NATURAL
     , MUX.MUNI_ST_NOME       MUNICIPIO_NATURAL
     , CURX.CUR_ST_NOME || CASE NVL(CURX.CUR_ST_HABILITACAO,'X')
                            WHEN 'X' THEN ', '
                            ELSE ', '||CURX.CUR_ST_HABILITACAO||', '
                           END ||' reconhecido pela Portaria '||CURX.CUR_ST_AUTORIZACAO_MEC||' de '||TO_CHAR(CURX.CUR_DT_AUTORIZACAO,'DD/MM/YYYY')||', '||
       'publicada no Diário Oficial da União em '||TO_CHAR(CURX.CUR_DT_PUBLICA_DOU,'DD/MM/YYYY') CURSO_TEXTO
     , HIS.PERI_ST_NOME
     , HIS.ANO
     , HIS.SEQ
     , HIS.DISC_ST_NOME
     , NVL(HIS.SITUACAO,'-') SITUACAO
     , NVL(HIS.SITUACAO_PRATICA,'-') SITUACAO_PRATICA
     , HIS.FALTAS
     , HIS.MEDIA
     , HIS.CARGA_HORARIA CARGA_HORARIA_CUMPRIDA
     , INST.INST_ST_NOME_DIRET
     , INST.INST_ST_NOME_SECRET
 FROM TBL_ALUNO_CURSO ACURX
INNER JOIN TBL_ALUNO  ALUX ON ALUX.ALU_IN_ID = ACURX.ALU_IN_ID
INNER JOIN TBL_CURSO  CURX ON CURX.CUR_IN_ID = ACURX.CUR_IN_ID
INNER JOIN TBL_INSTITUICAO INST ON INST.INST_IN_ID = CURX.INST_IN_ID
INNER JOIN TBL_UF     UFX  ON UFX.UF_IN_CODIGO_CENSO = ALUX.ALU_IN_UF_NASCIMENTO
LEFT  JOIN TBL_MUNICIPIO MUX ON MUX.MUNI_IN_CODIGO_CENSO = ALUX.ALU_IN_MUNI_NASCIMENTO
INNER JOIN
     (SELECT ACHIS.ACUR_IN_ID, PER.PERI_ST_NOME , TO_CHAR(PER.PERI_DT_INICIO, 'YYYY') AS ANO, GRD.GRD_IN_SEQUENCIA SEQ, DIS.DISC_ST_NOME
     , FC_REFERENCIA_DESCRICAO('SITUACAO_HISTORICO',ACHIS.ACHIS_IN_SITUACAO) SITUACAO
     , FC_REFERENCIA_DESCRICAO('SITUACAO_PRATICA',ACHIS.ACHIS_IN_SITUACAO_PRATICA) SITUACAO_PRATICA
     , NVL(ACHIS.ACHIS_IN_FALTA,0) FALTAS        , ACHIS.ACHIS_NU_MEDIA MEDIA
     , NVL(ACHIS.ACHIS_NU_CHTEORICA_CUMPRIDA,0) CARGA_HORARIA
  FROM TBL_ALUNO_CURSO_HISTORICO ACHIS
 INNER JOIN TBL_ALUNO_CURSO ACUR ON ACUR.ACUR_IN_ID = ACHIS.ACUR_IN_ID 
 INNER JOIN TBL_DISCIPLINA DIS ON DIS.DISC_IN_ID = ACHIS.DISC_IN_ID
 INNER JOIN TBL_PERIODO PER ON PER.PERI_IN_ID = ACHIS.PERI_IN_ID
  LEFT JOIN TBL_GRADE GRD ON GRD.DISC_IN_ID = ACHIS.DISC_IN_ID
                         AND GRD.CURR_IN_ID = FC_GET_CURRICULO(ACUR.TUR_IN_ID)
                         AND GRD.CURR_IN_ID = ACHIS.CURR_IN_ID
                         AND GRD.PERI_IN_ID = ACHIS.PERI_IN_ID
 WHERE ACHIS.ACUR_IN_ID = $P!{P50_ACUR_IN_ID}
UNION
SELECT 3 ACUR_IN_ID, PER.PERI_ST_NOME, TO_CHAR(PER.PERI_DT_INICIO, 'YYYY') AS ANO, GRD.GRD_IN_SEQUENCIA SEQ, DIS.DISC_ST_NOME
     , FC_REFERENCIA_DESCRICAO('SITUACAO_HISTORICO',1) SITUACAO
     , ' ' SITUACAO_PRATICA
     , 0 FALTAS, NULL MEDIA
     , 0 CARGA_HORARIA
  FROM TBL_GRADE GRD
 INNER JOIN TBL_DISCIPLINA DIS ON DIS.DISC_IN_ID = GRD.DISC_IN_ID
 INNER JOIN TBL_PERIODO PER ON PER.PERI_IN_ID = GRD.PERI_IN_ID
 INNER JOIN TBL_ALUNO_CURSO ACUR ON FC_GET_CURRICULO(ACUR.TUR_IN_ID) = GRD.CURR_IN_ID
 WHERE ACUR.ACUR_IN_ID = $P!{P50_ACUR_IN_ID}
   AND GRD.GRD_IN_ID NOT IN (SELECT GRD2.GRD_IN_ID
                               FROM TBL_GRADE GRD2
                              INNER JOIN TBL_ALUNO_CURSO_HISTORICO ACHI2 ON ACHI2.PERI_IN_ID = GRD2.PERI_IN_ID
                                                                        AND ACHI2.DISC_IN_ID = GRD2.DISC_IN_ID
                                                                        AND ACHI2.CURR_IN_ID = GRD2.CURR_IN_ID
                              INNER JOIN TBL_ALUNO_CURSO ACUR            ON ACUR.ACUR_IN_ID  = ACHI2.ACUR_IN_ID
                             WHERE ACUR.ACUR_IN_ID = $P!{P50_ACUR_IN_ID}
                               AND FC_GET_CURRICULO(ACUR.TUR_IN_ID) = ACHI2.CURR_IN_ID)
ORDER BY 2, 3) HIS ON HIS.ACUR_IN_ID = ACURX.ACUR_IN_ID
WHERE ACURX.ACUR_IN_ID = $P!{P50_ACUR_IN_ID}