SELECT  -- "ALUNO"."ALU_IN_ID",
         "ALUNO"."ALU_IN_CPF",
        -- "ALUNO"."ALU_ST_RG" ,
         "ALUNO"."ALU_DT_NASCIMENTO" ,
         "ALUNO"."ALU_ST_NOME" , 
         "ALUNO"."ALU_ST_NOME_MAE",
         -- "CURSO"."CUR_ST_NOME",
         -- "CURSO"."CUR_ST_AUTORIZACAO_MEC" "CUR_ST_PORTARIA",
         -- TO_CHAR("CURSO"."CUR_DT_AUTORIZACAO",'DD/MM/YYYY') "CUR_DT_AUTORIZACAO",
         -- TO_CHAR("CURSO"."CUR_DT_PUBLICA_DOU",'DD/MM/YYYY') "CUR_DT_PUBLICA_DOU",
         "PERIODO"."PERI_ST_NOME",
         "TURNO"."TURN_ST_DESCRICAO",
         MIN("TAULA"."AULA_CH_HORA_INI") "INICIO_AULA",
         MAX("TAULA"."AULA_CH_HORA_FIM") "FIM_AULA"
  FROM SAXIE."TBL_ALUNO" "ALUNO"
 INNER JOIN SAXIE."TBL_ALUNO_CURSO" "ALUNO_CURSO" ON "ALUNO_CURSO"."ALU_IN_ID" = "ALUNO"."ALU_IN_ID"
 INNER JOIN SAXIE."TBL_MATRICULA" "MATRICULA" ON "MATRICULA"."ACUR_IN_ID" = "ALUNO_CURSO"."ACUR_IN_ID"
 INNER JOIN SAXIE."TBL_PERIODO" "PERIODO" ON "PERIODO"."PERI_IN_ID" = "MATRICULA"."PERI_IN_ID"
 INNER JOIN SAXIE."TBL_CURSO" "CURSO" ON "CURSO"."CUR_IN_ID" = "ALUNO_CURSO"."CUR_IN_ID"
 INNER JOIN SAXIE."TBL_CURSO_TURNO" "CTURNO" ON "CTURNO"."CUR_IN_ID" = "CURSO"."CUR_IN_ID"
 INNER JOIN SAXIE."TBL_TURNO" "TURNO" ON "TURNO"."TURN_IN_ID" = "CTURNO"."TURN_IN_ID"
 INNER JOIN SAXIE."TBL_TURNO_AULA" "TAULA" ON "TAULA"."TURN_IN_ID" = "TURNO"."TURN_IN_ID"
 INNER JOIN SAXIE."TBL_TURMA" "TUR" ON "TUR"."TUR_IN_ID" = "ALUNO_CURSO"."TUR_IN_ID"
                                   AND "TUR"."CUR_IN_ID" = "ALUNO_CURSO"."CUR_IN_ID"
                                   AND "TUR"."TURN_IN_ID" = "TURNO"."TURN_IN_ID"                               
  WHERE "ALUNO_CURSO"."ACUR_IN_ID"= &&p_acur_in_id
    AND "MATRICULA"."MATR_IN_SITUACAO" = 2
  GROUP BY "ALUNO"."ALU_IN_ID",
         "ALUNO"."ALU_IN_CPF",
         "ALUNO"."ALU_ST_RG" ,
         "ALUNO"."ALU_DT_NASCIMENTO" ,
         "ALUNO"."ALU_ST_NOME" , 
         "ALUNO"."ALU_ST_NOME_MAE",
         "CURSO"."CUR_ST_NOME",
         "CURSO"."CUR_ST_AUTORIZACAO_MEC",
         TO_CHAR("CURSO"."CUR_DT_AUTORIZACAO",'DD/MM/YYYY'),
         TO_CHAR("CURSO"."CUR_DT_PUBLICA_DOU",'DD/MM/YYYY'),
         "PERIODO"."PERI_ST_NOME",
         "TURNO"."TURN_ST_DESCRICAO"