DROP TABLESPACE TS_APEX INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TS_DATA INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TS_INDX INCLUDING CONTENTS AND DATAFILES;


CREATE TABLESPACE TS_APEX DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\tsapex01.dbf' SIZE 100M AUTOEXTEND ON NEXT 1M;
CREATE TABLESPACE TS_DATA DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\tsdata01.dbf' SIZE 100M AUTOEXTEND ON NEXT 1M;
CREATE TABLESPACE TS_INDX DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\tsindex01.dbf' SIZE 100M AUTOEXTEND ON NEXT 1M;

