CREATE OR REPLACE VIEW VW_CURSO_DOCENTE AS
SELECT 
       CD.DCUR_IN_ID,
	   CD.CUR_IN_ID, 
       C.CUR_ST_NOME, 
	   CD.DOCE_IN_ID, 
	   D.DOCE_ST_NOME,
       D.DOCE_IN_MATRICULA,
	   CD.user_st_atualiza,
	   CD.user_dt_atualiza
  FROM  TBL_DOCENTE_CURSO CD
 INNER JOIN TBL_CURSO C
    ON C.CUR_IN_ID = CD.CUR_IN_ID
 INNER JOIN TBL_DOCENTE D
    ON D.DOCE_IN_ID = CD.DOCE_IN_ID;
	
GRANT SELECT ON VW_CURSO_DOCENTE TO PUBLIC;	